[package]
name = "tunnel_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "pytunnel"
crate-type = ["cdylib"]

[dependencies]
pollster = "0.4.0"
pyo3 = { version = "0.27.0", features = ["abi3-py310"] }
tunnel = { path = "../" }
