[package]
name = "tunnel_js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.83"
tunnel = { path = "../" }
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.56"
